using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Migrations.Operations;

namespace Laraue.EfCoreTriggers.SqlServer.Migrations
{
    /// <summary>
    /// Decorates an <see cref="IMigrationsSqlGenerator"/> so CREATE/ALTER/DROP TRIGGER statements
    /// generated by this library are wrapped in EXEC(...). SQL Server only allows these statements
    /// to be the first statement of a batch, so without this they fail whenever a migration is
    /// applied as an idempotent script (e.g. via Database.Migrate() or
    /// `dotnet ef migrations script --idempotent`), which nests them inside an IF block.
    /// This wraps whichever generator is already registered instead of replacing it, so it
    /// composes with a consumer's own custom <see cref="IMigrationsSqlGenerator"/>.
    /// </summary>
    public class TriggerSqlMigrationsSqlGenerator : IMigrationsSqlGenerator
    {
        private readonly IMigrationsSqlGenerator _inner;

        public TriggerSqlMigrationsSqlGenerator(IMigrationsSqlGenerator inner)
        {
            _inner = inner;
        }

        public IReadOnlyList<MigrationCommand> Generate(
            IReadOnlyList<MigrationOperation> operations,
            IModel model = null,
            MigrationsSqlGenerationOptions options = MigrationsSqlGenerationOptions.Default)
        {
            var wrappedOperations = operations
                .Select(WrapIfTriggerSql)
                .ToArray();

            return _inner.Generate(wrappedOperations, model, options);
        }

        private static MigrationOperation WrapIfTriggerSql(MigrationOperation operation)
        {
            if (operation is not SqlOperation sqlOperation || sqlOperation.Sql is null)
            {
                return operation;
            }

            var trimmedSql = sqlOperation.Sql.TrimStart();

            var isTriggerDdl = trimmedSql.StartsWith("CREATE TRIGGER", StringComparison.OrdinalIgnoreCase)
                || trimmedSql.StartsWith("ALTER TRIGGER", StringComparison.OrdinalIgnoreCase)
                || trimmedSql.StartsWith("DROP TRIGGER", StringComparison.OrdinalIgnoreCase);

            if (!isTriggerDdl)
            {
                return operation;
            }

            var escapedSql = sqlOperation.Sql.Replace("'", "''", StringComparison.Ordinal);

            return new SqlOperation
            {
                Sql = $"EXEC(N'{escapedSql}')",
                SuppressTransaction = sqlOperation.SuppressTransaction,
                IsDestructiveChange = sqlOperation.IsDestructiveChange,
            };
        }
    }
}
